DefaultContentLanguage = "en"

baseURL = "https://aurora-sharing-science.github.io/aurora-blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Lorena De León - All rights reserved"
enableEmoji = true
#publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1

[languages]

  [languages.en]

    languageCode = "en"
    languageName = "en"
    weight = 1
    title = "Aurora sharing science"

    [languages.en.params]
      logo = "images/logo.jpg"
      description ="a blog to share science about our planet"
      #mailchimp = "you can provide a mailchimp-link here"

    [languages.en.params.author]
      name = "Lorena De León"
      thumbnail = "images/author.jpg"
      description = "Geoscientist and writer"

    [languages.en.params.index]
      picture = "images/logo.jpg"
      title = "Aurora sharing science"
      subtitle = "Earth Sciences communication for everyone"
      mdtext = """**Making science straightforward and relevant**"""
      alertbar = false

    [languages.en.params.social]
      github = "aurora-sharing-science"
      #linkedin = "<username>"
      #xing = "<username>"
      #medium = "<username>"
      #twitter = "<username>"
      instagram = "aurora.sharing.science"

    ## Main Menu
    [[languages.en.menu.main]]
        name = "Blog"
        weight = 100
        identifier = "blog"
        url = "/blog"
    #[[menu.main]]
    #    name = "Separate"
    #    weight = 100
    #    identifier = "separate"
    #    url = "/separate"
    [[languages.en.menu.main]]
        name = "About"
        identifier = "about"
        weight = 200
        url = "/"
    #[[menu.main]]
    #    name = "Imprint"
    #    identifier = "imprint"
    #    weight = 200
    #    url = "/static/imprint"

  [languages.es]

    languageCode = "es"
    languageName = "es"
    weight = 2
    title = "Aurora sharing science"

    [languages.es.params]
      logo = "images/logo.jpg"
      description ="Un blog para compartir la ciencia de nuestro planeta"
      #mailchimp = "you can provide a mailchimp-link here"

    [languages.es.params.author]
      name = "Lorena De León"
      thumbnail = "images/author.jpg"
      description = "Geocientífica y escritora"

    [languages.es.params.index]
      picture = "images/logo.jpg"
      title = "Aurora sharing science"
      subtitle = "Divulgación de las Ciencias de la Tierra"
      mdtext = """**Haciendo que la ciencia sea clara y relevante**"""
      alertbar = false

    [languages.es.params.social]
      github = "<username>"
      #linkedin = "<username>"
      #xing = "<username>"
      #medium = "<username>"
      #twitter = "<username>"
      instagram = "<username>"

    ## Main Menu
    [[languages.es.menu.main]]
        name = "Blog"
        weight = 100
        identifier = "blog"
        url = "/es/blog"
    #[[menu.main]]
    #    name = "Separate"
    #    weight = 100
    #    identifier = "separate"
    #    url = "/separate"
    [[languages.es.menu.main]]
        name = "Acerca de"
        identifier = "about"
        weight = 200
        url = "/es/"
    #[[menu.main]]
    #    name = "Imprint"
    #    identifier = "imprint"
    #    weight = 200
    #    url = "/static/imprint"